// svelte-hono/build — the build helper.
//
// Two esbuild passes plus one generated file:
//   1. Client bundles (one per component, browser ESM, self-contained).
//   2. A `bundles.generated.ts` written next to the worker entry. The user's
//      worker imports it normally — no globals, no esbuild `define`, no
//      `declare const` boilerplate.
//   3. Worker bundle (Workers-target ESM) that imports the generated file
//      along with the user's Svelte components.
//
// Usage (in your project's build.mjs):
//
//   import { buildHonoSvelte } from "svelte-hono/build";
//
//   await buildHonoSvelte({
//     workerEntry: "./worker.ts",
//     outDir: "./build",
//     components: {
//       hello: "./hello.svelte",
//       about: "./about.svelte",
//     },
//   });
//
// Then in worker.ts:
//
//   import { bundles } from "./bundles.generated";
//   attachSvelteRoutes(app, { bundles });
//
// Add `bundles.generated.ts` to .gitignore — it's regenerated each build.

import { build } from "esbuild";
import sveltePlugin from "esbuild-svelte";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export interface BuildHonoSvelteOptions {
  /** Path to the Worker entry (TS or JS). */
  workerEntry: string;
  /** Output directory; will hold `worker.bundled.mjs` + intermediates. */
  outDir: string;
  /** Map of component id (the `hydrateAs` key) -> path to .svelte file. */
  components: Record<string, string>;
  /** ECMAScript target. Defaults to "es2022" (Workers-compatible). */
  target?: string;
  /** Set true for source maps + non-minified output. */
  dev?: boolean;
  /**
   * Filename of the generated bundles module, relative to the worker entry's
   * directory. Defaults to "bundles.generated.ts". The user imports from
   * this path (without extension) in their worker.
   */
  bundlesFile?: string;
}

export interface BuildHonoSvelteResult {
  workerOutfile: string;
  bundleSizes: Record<string, { js: number; css: number }>;
  workerBytes: number;
  bundlesFile: string;
}

export async function buildHonoSvelte(
  options: BuildHonoSvelteOptions,
): Promise<BuildHonoSvelteResult> {
  const target = options.target ?? "es2022";
  const dev = options.dev ?? false;
  const outDir = resolve(options.outDir);
  const workerEntry = resolve(options.workerEntry);
  const workerDir = dirname(workerEntry);
  const bundlesFile = options.bundlesFile ?? "bundles.generated.ts";
  const bundlesFilePath = resolve(workerDir, bundlesFile);

  mkdirSync(outDir, { recursive: true });

  const sveltePluginClient = sveltePlugin({
    compilerOptions: { generate: "client", dev, css: "external" },
  });
  const sveltePluginServer = sveltePlugin({
    compilerOptions: { generate: "server", dev, css: "external" },
  });

  // ── 1. Build each component's client bundle (browser ESM). ──────────────
  const bundles: Record<string, { js: string; css: string }> = {};

  for (const [id, componentPath] of Object.entries(options.components)) {
    const resolved = resolve(workerDir, componentPath);
    const entryShim = join(outDir, `_client-entry-${id}.js`);
    writeFileSync(
      entryShim,
      `import Component from ${JSON.stringify(resolved)};
import { hydrate as _hydrate } from "svelte";
export function hydrate(props) {
  return _hydrate(Component, {
    target: document.getElementById("svelte-hono-root"),
    props,
  });
}
`,
    );
    const clientOutfile = join(outDir, `client-${id}.js`);
    await build({
      entryPoints: [entryShim],
      bundle: true,
      format: "esm",
      platform: "browser",
      target,
      outfile: clientOutfile,
      minify: !dev,
      sourcemap: dev,
      plugins: [sveltePluginClient],
      logLevel: "silent",
    });
    const js = readFileSync(clientOutfile, "utf8");
    let css = "";
    try {
      css = readFileSync(clientOutfile.replace(/\.js$/, ".css"), "utf8");
    } catch {
      css = "";
    }
    bundles[id] = { js, css };
  }

  // ── 2. Write bundles.generated.ts next to the worker entry. ─────────────
  // Plain ES module the worker imports. No globals, no define, no magic.
  writeFileSync(
    bundlesFilePath,
    `// Generated by svelte-hono/build. Do not edit. Regenerated on every build.\n` +
      `// Add this file to .gitignore.\n` +
      `import type { ClientBundle } from "svelte-hono";\n\n` +
      `export const bundles: Record<string, ClientBundle> = ${JSON.stringify(bundles, null, 2)};\n`,
  );

  // ── 3. Bundle the worker. ───────────────────────────────────────────────
  const workerOutfile = join(outDir, "worker.bundled.mjs");
  await build({
    entryPoints: [workerEntry],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target,
    outfile: workerOutfile,
    minify: !dev,
    sourcemap: dev,
    plugins: [sveltePluginServer],
    external: ["cloudflare:workers"],
    logLevel: "silent",
  });

  const workerBytes = readFileSync(workerOutfile).byteLength;
  const bundleSizes: BuildHonoSvelteResult["bundleSizes"] = {};
  for (const [id, b] of Object.entries(bundles)) {
    bundleSizes[id] = { js: b.js.length, css: b.css.length };
  }

  return { workerOutfile, bundleSizes, workerBytes, bundlesFile: bundlesFilePath };
}
